# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(564, 513)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectedFrame = QtWidgets.QFrame(self.centralwidget)
        self.connectedFrame.setEnabled(True)
        self.connectedFrame.setGeometry(QtCore.QRect(0, 60, 571, 461))
        self.connectedFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connectedFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectedFrame.setObjectName("connectedFrame")
        self.DebugBordButtons = QtWidgets.QGroupBox(self.connectedFrame)
        self.DebugBordButtons.setEnabled(True)
        self.DebugBordButtons.setGeometry(QtCore.QRect(-1, 60, 561, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DebugBordButtons.setFont(font)
        self.DebugBordButtons.setAlignment(QtCore.Qt.AlignCenter)
        self.DebugBordButtons.setFlat(False)
        self.DebugBordButtons.setCheckable(False)
        self.DebugBordButtons.setObjectName("DebugBordButtons")
        self.FlashButton = QtWidgets.QPushButton(self.DebugBordButtons)
        self.FlashButton.setEnabled(False)
        self.FlashButton.setGeometry(QtCore.QRect(30, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FlashButton.setFont(font)
        self.FlashButton.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.FlashButton.setObjectName("FlashButton")
        self.RunButton = QtWidgets.QPushButton(self.DebugBordButtons)
        self.RunButton.setEnabled(True)
        self.RunButton.setGeometry(QtCore.QRect(380, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RunButton.setFont(font)
        self.RunButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.RunButton.setObjectName("RunButton")
        self.PowerOptions = QtWidgets.QGroupBox(self.connectedFrame)
        self.PowerOptions.setGeometry(QtCore.QRect(-1, 170, 561, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PowerOptions.setFont(font)
        self.PowerOptions.setAlignment(QtCore.Qt.AlignCenter)
        self.PowerOptions.setFlat(False)
        self.PowerOptions.setCheckable(False)
        self.PowerOptions.setObjectName("PowerOptions")
        self.RestartPowerButton = QtWidgets.QPushButton(self.PowerOptions)
        self.RestartPowerButton.setGeometry(QtCore.QRect(210, 50, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RestartPowerButton.setFont(font)
        self.RestartPowerButton.setObjectName("RestartPowerButton")
        self.DelayValue = QtWidgets.QTextEdit(self.PowerOptions)
        self.DelayValue.setGeometry(QtCore.QRect(280, 20, 20, 20))
        self.DelayValue.setAcceptDrops(True)
        self.DelayValue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DelayValue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DelayValue.setObjectName("DelayValue")
        self.DelaySeconds = QtWidgets.QLabel(self.PowerOptions)
        self.DelaySeconds.setGeometry(QtCore.QRect(210, 22, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DelaySeconds.setFont(font)
        self.DelaySeconds.setObjectName("DelaySeconds")
        self.offButton = QtWidgets.QPushButton(self.PowerOptions)
        self.offButton.setEnabled(False)
        self.offButton.setGeometry(QtCore.QRect(30, 54, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.offButton.setFont(font)
        self.offButton.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.offButton.setObjectName("offButton")
        self.onButton = QtWidgets.QPushButton(self.PowerOptions)
        self.onButton.setGeometry(QtCore.QRect(30, 12, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.onButton.setFont(font)
        self.onButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.onButton.setObjectName("onButton")
        self.FastRestart = QtWidgets.QPushButton(self.PowerOptions)
        self.FastRestart.setGeometry(QtCore.QRect(440, 20, 90, 72))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FastRestart.setFont(font)
        self.FastRestart.setObjectName("FastRestart")
        self.OutputBoxLable = QtWidgets.QLabel(self.connectedFrame)
        self.OutputBoxLable.setGeometry(QtCore.QRect(30, 290, 501, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OutputBoxLable.setFont(font)
        self.OutputBoxLable.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputBoxLable.setObjectName("OutputBoxLable")
        self.OutputBox = QtWidgets.QPlainTextEdit(self.connectedFrame)
        self.OutputBox.setGeometry(QtCore.QRect(30, 330, 501, 71))
        self.OutputBox.setObjectName("OutputBox")
        self.DisconnectButton = QtWidgets.QPushButton(self.connectedFrame)
        self.DisconnectButton.setGeometry(QtCore.QRect(380, 0, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DisconnectButton.setFont(font)
        self.DisconnectButton.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.disconnectFrame = QtWidgets.QFrame(self.centralwidget)
        self.disconnectFrame.setGeometry(QtCore.QRect(0, 0, 561, 61))
        self.disconnectFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.disconnectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disconnectFrame.setObjectName("disconnectFrame")
        self.COM_List = QtWidgets.QComboBox(self.disconnectFrame)
        self.COM_List.setGeometry(QtCore.QRect(80, 30, 121, 22))
        self.COM_List.setObjectName("COM_List")
        self.SelectCom = QtWidgets.QLabel(self.disconnectFrame)
        self.SelectCom.setGeometry(QtCore.QRect(100, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SelectCom.setFont(font)
        self.SelectCom.setObjectName("SelectCom")
        self.ReloadButton = QtWidgets.QPushButton(self.disconnectFrame)
        self.ReloadButton.setGeometry(QtCore.QRect(30, 30, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ReloadButton.setFont(font)
        self.ReloadButton.setObjectName("ReloadButton")
        self.ConnectButton = QtWidgets.QPushButton(self.disconnectFrame)
        self.ConnectButton.setGeometry(QtCore.QRect(380, 20, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.ConnectButton.setObjectName("ConnectButton")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.DelayValue, self.RestartPowerButton)
        mainWindow.setTabOrder(self.RestartPowerButton, self.FastRestart)
        mainWindow.setTabOrder(self.FastRestart, self.onButton)
        mainWindow.setTabOrder(self.onButton, self.offButton)
        mainWindow.setTabOrder(self.offButton, self.OutputBox)
        mainWindow.setTabOrder(self.OutputBox, self.FlashButton)
        mainWindow.setTabOrder(self.FlashButton, self.RunButton)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.DebugBordButtons.setTitle(_translate("mainWindow", "Debug Bord Buttons"))
        self.FlashButton.setText(_translate("mainWindow", "Flash"))
        self.RunButton.setText(_translate("mainWindow", "Run"))
        self.PowerOptions.setTitle(_translate("mainWindow", "Power Options"))
        self.RestartPowerButton.setText(_translate("mainWindow", "Restart Power"))
        self.DelaySeconds.setText(_translate("mainWindow", "Delay (s)"))
        self.offButton.setText(_translate("mainWindow", "OFF"))
        self.onButton.setText(_translate("mainWindow", "ON"))
        self.FastRestart.setText(_translate("mainWindow", "Fast\n"
"Restart"))
        self.OutputBoxLable.setText(_translate("mainWindow", "OUTPUT BOX"))
        self.OutputBox.setPlainText(_translate("mainWindow", "Nothing"))
        self.DisconnectButton.setText(_translate("mainWindow", "Disconnect"))
        self.SelectCom.setText(_translate("mainWindow", "Select COM"))
        self.ReloadButton.setText(_translate("mainWindow", "Reload"))
        self.ConnectButton.setText(_translate("mainWindow", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
