# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(564, 513)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DebugBordButtons = QtWidgets.QGroupBox(self.centralwidget)
        self.DebugBordButtons.setGeometry(QtCore.QRect(40, 130, 500, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DebugBordButtons.setFont(font)
        self.DebugBordButtons.setAlignment(QtCore.Qt.AlignCenter)
        self.DebugBordButtons.setFlat(False)
        self.DebugBordButtons.setCheckable(False)
        self.DebugBordButtons.setObjectName("DebugBordButtons")
        self.FlashButton = QtWidgets.QPushButton(self.DebugBordButtons)
        self.FlashButton.setGeometry(QtCore.QRect(50, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FlashButton.setFont(font)
        self.FlashButton.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.FlashButton.setObjectName("FlashButton")
        self.RunButton = QtWidgets.QPushButton(self.DebugBordButtons)
        self.RunButton.setGeometry(QtCore.QRect(300, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RunButton.setFont(font)
        self.RunButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.RunButton.setObjectName("RunButton")
        self.PowerOptions = QtWidgets.QGroupBox(self.centralwidget)
        self.PowerOptions.setGeometry(QtCore.QRect(40, 260, 500, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PowerOptions.setFont(font)
        self.PowerOptions.setAlignment(QtCore.Qt.AlignCenter)
        self.PowerOptions.setFlat(False)
        self.PowerOptions.setCheckable(False)
        self.PowerOptions.setObjectName("PowerOptions")
        self.RestartPowerButton = QtWidgets.QPushButton(self.PowerOptions)
        self.RestartPowerButton.setGeometry(QtCore.QRect(175, 50, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RestartPowerButton.setFont(font)
        self.RestartPowerButton.setObjectName("RestartPowerButton")
        self.DelayValue = QtWidgets.QTextEdit(self.PowerOptions)
        self.DelayValue.setGeometry(QtCore.QRect(240, 20, 20, 20))
        self.DelayValue.setAcceptDrops(True)
        self.DelayValue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DelayValue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DelayValue.setObjectName("DelayValue")
        self.DelaySeconds = QtWidgets.QLabel(self.PowerOptions)
        self.DelaySeconds.setGeometry(QtCore.QRect(178, 22, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DelaySeconds.setFont(font)
        self.DelaySeconds.setObjectName("DelaySeconds")
        self.offButton = QtWidgets.QPushButton(self.PowerOptions)
        self.offButton.setGeometry(QtCore.QRect(10, 54, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.offButton.setFont(font)
        self.offButton.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.offButton.setObjectName("offButton")
        self.onButton = QtWidgets.QPushButton(self.PowerOptions)
        self.onButton.setGeometry(QtCore.QRect(10, 12, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.onButton.setFont(font)
        self.onButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.onButton.setObjectName("onButton")
        self.FastRestart = QtWidgets.QPushButton(self.PowerOptions)
        self.FastRestart.setGeometry(QtCore.QRect(400, 20, 90, 72))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FastRestart.setFont(font)
        self.FastRestart.setObjectName("FastRestart")
        self.SerialOptions = QtWidgets.QGroupBox(self.centralwidget)
        self.SerialOptions.setGeometry(QtCore.QRect(40, 10, 500, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SerialOptions.setFont(font)
        self.SerialOptions.setAlignment(QtCore.Qt.AlignCenter)
        self.SerialOptions.setFlat(False)
        self.SerialOptions.setCheckable(False)
        self.SerialOptions.setObjectName("SerialOptions")
        self.COM_List = QtWidgets.QComboBox(self.SerialOptions)
        self.COM_List.setGeometry(QtCore.QRect(50, 40, 121, 22))
        self.COM_List.setObjectName("COM_List")
        self.SelectCom = QtWidgets.QLabel(self.SerialOptions)
        self.SelectCom.setGeometry(QtCore.QRect(70, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SelectCom.setFont(font)
        self.SelectCom.setObjectName("SelectCom")
        self.DisconnectButton = QtWidgets.QPushButton(self.SerialOptions)
        self.DisconnectButton.setGeometry(QtCore.QRect(350, 50, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DisconnectButton.setFont(font)
        self.DisconnectButton.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.ConnectButton = QtWidgets.QPushButton(self.SerialOptions)
        self.ConnectButton.setGeometry(QtCore.QRect(350, 10, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.ConnectButton.setObjectName("ConnectButton")
        self.ReloadButton = QtWidgets.QPushButton(self.SerialOptions)
        self.ReloadButton.setGeometry(QtCore.QRect(5, 42, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ReloadButton.setFont(font)
        self.ReloadButton.setObjectName("ReloadButton")
        self.OutputBoxLable = QtWidgets.QLabel(self.centralwidget)
        self.OutputBoxLable.setGeometry(QtCore.QRect(40, 380, 501, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OutputBoxLable.setFont(font)
        self.OutputBoxLable.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputBoxLable.setObjectName("OutputBoxLable")
        self.OutputBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.OutputBox.setGeometry(QtCore.QRect(40, 410, 501, 71))
        self.OutputBox.setObjectName("OutputBox")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.DebugBordButtons.setTitle(_translate("mainWindow", "Debug Bord Buttons"))
        self.FlashButton.setText(_translate("mainWindow", "Flash"))
        self.RunButton.setText(_translate("mainWindow", "Run"))
        self.PowerOptions.setTitle(_translate("mainWindow", "Power Options"))
        self.RestartPowerButton.setText(_translate("mainWindow", "Restart Power"))
        self.DelaySeconds.setText(_translate("mainWindow", "Delay (s)"))
        self.offButton.setText(_translate("mainWindow", "OFF"))
        self.onButton.setText(_translate("mainWindow", "ON"))
        self.FastRestart.setText(_translate("mainWindow", "Fast\n"
"Restart"))
        self.SerialOptions.setTitle(_translate("mainWindow", "Serial Options"))
        self.SelectCom.setText(_translate("mainWindow", "Select COM"))
        self.DisconnectButton.setText(_translate("mainWindow", "Disconnect"))
        self.ConnectButton.setText(_translate("mainWindow", "Connect"))
        self.ReloadButton.setText(_translate("mainWindow", "Reload"))
        self.OutputBoxLable.setText(_translate("mainWindow", "OUTPUT BOX"))
        self.OutputBox.setPlainText(_translate("mainWindow", "Nothing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
